name: Deploy github pages

on:
  push:
    branches:
      - frontend-master
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Deploy github pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo ${{ vars.API_URL }}

      - name: Set up node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
      - run: npm ci
      - run: npm run build
      - run: sed -i "s~API_URL_PLACEHOLDER~${{ vars.API_URL }}~g" ./dist/index.html

      - name: Set up pages
        uses: actions/configure-pages@v2
      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
      
      - name: Deploy github pages
        id: deployment
        uses: actions/deploy-pages@v2

